# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200515_1505'),
        ('courses', '0002_auto_20200510_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='organization.CourseOrg', verbose_name='课程机构'),
        ),
    ]
