# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='', max_length=300, verbose_name='老师告诉你课程须知'),
        ),
    ]
