# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-25 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200524_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='手机'),
        ),
    ]
